# Generated by Django 4.2.17 on 2024-12-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Prediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.IntegerField()),
                ("tenure", models.IntegerField()),
                ("age", models.IntegerField()),
                ("marital", models.IntegerField()),
                ("address", models.IntegerField()),
                ("income", models.FloatField()),
                ("ed", models.IntegerField()),
                ("employ", models.IntegerField()),
                ("retire", models.FloatField()),
                ("gender", models.IntegerField()),
                ("reside", models.IntegerField()),
                ("prediction", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "predictions",
            },
        ),
    ]
